### ISSUE TITLE
Is it possible to use this to retrieve an arkose token to pass to GPT-4 requests?

### ISSUE THREAD

**Issue by munjyong** [noahcoolboy/funcaptcha#55]
I am trying to make a POST request to `https://chat.openai.com/backend-api/conversation`, which requires an `arkose_token` for GPT-4 requests.

I am looking to retrieve an arkose token in the form of:
```
1281785cfd1440558.9632456905|r=eu-west-1|meta=3|metabgclr=transparent|metaiconclr=%23757575|guitextcolor=%23000000|pk=35536E1E-65B4-4D96-9D97-6ADB7EFF8147|at=40|sup=1|rid=8|ag=101|cdn_url=https%3A%2F%2Ftcr9i.chat.openai.com%2Fcdn%2Ffc|lurl=https%3A%2F%2Faudio-eu-west-1.arkoselabs.com|surl=https%3A%2F%2Ftcr9i.chat.openai.com|smurl=https%3A%2F%2Ftcr9i.chat.openai.com%2Fcdn%2Ffc%2Fassets%2Fstyle-manager
```

How can I achieve this?

Thank you

**Comment by noahcoolboy** [comment]
Please read the docs!
getToken is the function which gets this very string.

**Comment by munjyong** [comment]
got it, thank you

could i get some advice on how i can import this package within an ES Modules based project?

i have tried:
```
import * as fun from 'funcaptcha'

...

  React.useEffect(() => {
    const getToken = async () => {
      const token = await fun
        .getToken({
          pkey: '35536E1E-65B4-4D96-9D97-6ADB7EFF8147', // The public key
          surl: 'https://tcr9i.chat.openai.com',
          headers: {
            'User-Agent':
              'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36',
          },
          site: 'https://chat.openai.com', // The site which contains the funcaptcha
        })
        .then((token) => {
          console.log('token!!!!!!!!!!', token)
        })

      console.log('token', token)
    }

    getToken()
  }, [])
  
...

```

but I am getting this error:
```
ReferenceError: process is not defined
    at node_modules/undici/lib/core/util.js (funcaptcha.js:445:34)
    at __require (chunk-KJ5TSSSV.js:12:50)
    at node_modules/undici/lib/client.js (funcaptcha.js:8029:16)
    at __require (chunk-KJ5TSSSV.js:12:50)
    at node_modules/undici/index.js (funcaptcha.js:17810:18)
    at __require (chunk-KJ5TSSSV.js:12:50)
    at node_modules/funcaptcha/lib/http.js (funcaptcha.js:17948:20)
    at __require (chunk-KJ5TSSSV.js:12:50)
    at node_modules/funcaptcha/lib/api.js (funcaptcha.js:18811:18)
    at __require (chunk-KJ5TSSSV.js:12:50)
```

Thank you very much for your help
